name: Lint & Typecheck

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm install
      - uses: actions/cache@v1
        id: cache-build
        with:
          path: "."
          key: ${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: install
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: "."
          key: ${{ github.sha }}
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck
    needs: install
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: "."
          key: ${{ github.sha }}
      - run: npm run typecheck
